import { DemoConfig } from './defaultConfig';

export const demos: Record<string, DemoConfig> = {
  salao: {
    id: 'salao',
    business: {
      name: 'Studio Bella',
      shortName: 'Bella',
      category: 'Salão de Beleza',
      tagline: 'Beleza no seu tempo com excelência',
      phone: '(51) 99842-1209',
      address: 'Rua Padre Chagas, 412 - Moinhos de Vento, Porto Alegre - RS',
      logoUrl: '/src/assets/logo.png',
      responsibleName: 'Mariana Costa',
      responsibleRole: 'Proprietária & Master Stylist',
    },
    terminology: {
      customer: 'Cliente',
      customers: 'Clientes',
      professional: 'Profissional',
      professionals: 'Profissionais',
      service: 'Serviço',
      services: 'Serviços',
      appointment: 'Agendamento',
      appointments: 'Agendamentos',
      attendance: 'Atendimento',
      attendances: 'Atendimentos',
      specialty: 'Especialidade',
      specialties: 'Especialidades',
    },
    features: {
      professionals: true,
      individualAgenda: true,
      approvalRequired: true,
      commissions: true,
      financial: true,
      reports: true,
      history: true,
      products: false,
      stock: false,
      reviews: true,
    },
    colors: {
      primary: '#7C3AED',
      primaryHover: '#6D28D9',
      secondary: '#F5F3FF',
      accent: '#10B981',
      background: '#FAF5FF',
      surface: '#FFFFFF',
      textPrimary: '#1E1B4B',
    },
  },

  barbearia: {
    id: 'barbearia',
    business: {
      name: 'Barber 88',
      shortName: 'Barber 88',
      category: 'Barbearia Clássica',
      tagline: 'Tradição, navalha afiada e cerveja gelada',
      phone: '(11) 98712-8800',
      address: 'Alameda Lorena, 880 - Jardins, São Paulo - SP',
      logoUrl: '/src/assets/logo.png',
      responsibleName: 'Rafael Costa',
      responsibleRole: 'Barbeiro Chefe & Fundador',
    },
    terminology: {
      customer: 'Cliente',
      customers: 'Clientes',
      professional: 'Barbeiro',
      professionals: 'Barbeiros',
      service: 'Serviço',
      services: 'Serviços',
      appointment: 'Horário',
      appointments: 'Horários',
      attendance: 'Atendimento',
      attendances: 'Atendimentos',
      specialty: 'Especialidade',
      specialties: 'Especialidades',
    },
    features: {
      professionals: true,
      individualAgenda: true,
      approvalRequired: false,
      commissions: true,
      financial: true,
      reports: true,
      history: true,
      products: true,
      stock: false,
      reviews: true,
    },
    colors: {
      primary: '#1E293B',
      primaryHover: '#0F172A',
      secondary: '#F1F5F9',
      accent: '#D97706',
      background: '#F8FAFC',
      surface: '#FFFFFF',
      textPrimary: '#0F172A',
    },
  },

  clinica: {
    id: 'clinica',
    business: {
      name: 'Clínica Horizonte',
      shortName: 'Horizonte',
      category: 'Clínica Médica Integrada',
      tagline: 'Cuidado humanizado e medicina preventiva',
      phone: '(21) 3209-4000',
      address: 'Av. das Américas, 3500 - Barra da Tijuca, Rio de Janeiro - RJ',
      logoUrl: '/src/assets/logo.png',
      responsibleName: 'Dra. Ana Ribeiro',
      responsibleRole: 'Diretora Clínica (CRM 52.89412-0)',
    },
    terminology: {
      customer: 'Paciente',
      customers: 'Pacientes',
      professional: 'Médico(a)',
      professionals: 'Corpo Clínico',
      service: 'Especialidade / Exame',
      services: 'Especialidades & Procedimentos',
      appointment: 'Consulta',
      appointments: 'Consultas',
      attendance: 'Atendimento',
      attendances: 'Atendimentos',
      specialty: 'Especialidade',
      specialties: 'Especialidades',
    },
    features: {
      professionals: true,
      individualAgenda: true,
      approvalRequired: true,
      commissions: false,
      financial: true,
      reports: true,
      history: true,
      products: false,
      stock: false,
      reviews: false,
    },
    colors: {
      primary: '#0284C7',
      primaryHover: '#0369A1',
      secondary: '#E0F2FE',
      accent: '#059669',
      background: '#F0F9FF',
      surface: '#FFFFFF',
      textPrimary: '#0C4A6E',
    },
  },

  estetica: {
    id: 'estetica',
    business: {
      name: 'Essenza Estética Avançada',
      shortName: 'Essenza',
      category: 'Clínica Estética & Bem-estar',
      tagline: 'Realçando sua beleza natural com tecnologia de ponta',
      phone: '(31) 99120-7766',
      address: 'Rua Fernandes Tourinho, 250 - Savassi, Belo Horizonte - MG',
      logoUrl: '/src/assets/logo.png',
      responsibleName: 'Dra. Luiza Valente',
      responsibleRole: 'Biomédica Esteta',
    },
    terminology: {
      customer: 'Cliente',
      customers: 'Clientes',
      professional: 'Especialista',
      professionals: 'Especialistas',
      service: 'Procedimento',
      services: 'Procedimentos',
      appointment: 'Sessão',
      appointments: 'Sessões',
      attendance: 'Atendimento',
      attendances: 'Atendimentos',
      specialty: 'Área de Atuação',
      specialties: 'Áreas de Atuação',
    },
    features: {
      professionals: true,
      individualAgenda: true,
      approvalRequired: true,
      commissions: true,
      financial: true,
      reports: true,
      history: true,
      products: true,
      stock: true,
      reviews: true,
    },
    colors: {
      primary: '#BE185D',
      primaryHover: '#9D174D',
      secondary: '#FCE7F3',
      accent: '#059669',
      background: '#FFF1F2',
      surface: '#FFFFFF',
      textPrimary: '#881337',
    },
  },

  psicologia: {
    id: 'psicologia',
    business: {
      name: 'Espaço Mente Psicologia',
      shortName: 'Espaço Mente',
      category: 'Consultório de Psicologia & Psicoterapia',
      tagline: 'Um espaço acolhedor e seguro para o seu autoconhecimento',
      phone: '(41) 98834-5511',
      address: 'Rua Comendador Araújo, 499 - Batel, Curitiba - PR',
      logoUrl: '/src/assets/logo.png',
      responsibleName: 'Dra. Fernanda Lima',
      responsibleRole: 'Psicóloga Clínica (CRP 08/21980)',
    },
    terminology: {
      customer: 'Paciente',
      customers: 'Pacientes',
      professional: 'Terapeuta',
      professionals: 'Terapeutas',
      service: 'Modalidade',
      services: 'Modalidades de Terapia',
      appointment: 'Sessão',
      appointments: 'Sessões',
      attendance: 'Consulta',
      attendances: 'Consultas',
      specialty: 'Abordagem Teórica',
      specialties: 'Abordagens',
    },
    features: {
      professionals: true,
      individualAgenda: true,
      approvalRequired: true,
      commissions: false,
      financial: true,
      reports: true,
      history: true,
      products: false,
      stock: false,
      reviews: false,
    },
    colors: {
      primary: '#0D9488',
      primaryHover: '#0F766E',
      secondary: '#CCFBF1',
      accent: '#4F46E5',
      background: '#F0FDFA',
      surface: '#FFFFFF',
      textPrimary: '#134E4A',
    },
  },

  petshop: {
    id: 'petshop',
    business: {
      name: 'PetCare & Estética Animal',
      shortName: 'PetCare',
      category: 'Centro de Estética e Cuidados Pet',
      tagline: 'Amor, cuidado e higiene com os melhores profissionais',
      phone: '(19) 99765-4321',
      address: 'Av. Orosimbo Maia, 1020 - Cambuí, Campinas - SP',
      logoUrl: '/src/assets/logo.png',
      responsibleName: 'Carlos Eduardo Mendes',
      responsibleRole: 'Gestor & Especialista Pet',
    },
    terminology: {
      customer: 'Tutor',
      customers: 'Tutores',
      professional: 'Profissional Pet',
      professionals: 'Groomers & Especialistas',
      service: 'Serviço Pet',
      services: 'Serviços & Banhos',
      appointment: 'Agendamento',
      appointments: 'Agendamentos',
      attendance: 'Atendimento',
      attendances: 'Atendimentos',
      specialty: 'Especialidade',
      specialties: 'Especialidades',
      petSingular: 'Pet / Animal',
      petPlural: 'Pets',
    },
    features: {
      professionals: true,
      individualAgenda: true,
      approvalRequired: false,
      commissions: true,
      financial: true,
      reports: true,
      history: true,
      products: true,
      stock: true,
      reviews: true,
    },
    colors: {
      primary: '#EA580C',
      primaryHover: '#C2410C',
      secondary: '#FFEDD5',
      accent: '#16A34A',
      background: '#FFF7ED',
      surface: '#FFFFFF',
      textPrimary: '#7C2D12',
    },
  },

  generico: {
    id: 'generico',
    business: {
      name: 'AtendeMais Hub',
      shortName: 'AtendeMais',
      category: 'Serviços & Atendimento',
      tagline: 'Gestão ágil de agendamentos e horários profissionais',
      phone: '(11) 4002-8922',
      address: 'Av. Paulista, 1000 - Bela Vista, São Paulo - SP',
      logoUrl: '/src/assets/logo.png',
      responsibleName: 'Rodrigo Silveira',
      responsibleRole: 'Gerente Operacional',
    },
    terminology: {
      customer: 'Cliente',
      customers: 'Clientes',
      professional: 'Consultor / Especialista',
      professionals: 'Consultores',
      service: 'Serviço',
      services: 'Serviços',
      appointment: 'Agendamento',
      appointments: 'Agendamentos',
      attendance: 'Atendimento',
      attendances: 'Atendimentos',
      specialty: 'Área',
      specialties: 'Áreas',
    },
    features: {
      professionals: true,
      individualAgenda: true,
      approvalRequired: true,
      commissions: true,
      financial: true,
      reports: true,
      history: true,
      products: false,
      stock: false,
      reviews: true,
    },
    colors: {
      primary: '#2563EB',
      primaryHover: '#1D4ED8',
      secondary: '#DBEAFE',
      accent: '#10B981',
      background: '#F8FAFC',
      surface: '#FFFFFF',
      textPrimary: '#0F172A',
    },
  },
};
